### ISSUE TITLE
Group Node Member Long Names

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel-recipes#14]
There seems to be an error generated when using long names, such as in this case "Alcorn Player" as a member of the Group Node.

```
05-03 10:37:00.92 (emit) Traceback (most recent call last):
05-03 10:37:00.92   File "C:\Nodel\TCM\.\nodes\TCM ISS Exercise Video - Exhibit\script.py", line 201, in <lambda>
05-03 10:37:00.92     memberStatusSignal.addEmitHandler(lambda arg: aggregateMemberStatus())
05-03 10:37:00.92   File "C:\Nodel\TCM\.\nodes\TCM ISS Exercise Video - Exhibit\script.py", line 170, in aggregateMemberStatus
05-03 10:37:00.92     memberLevel = memberStatus.get('level')
05-03 10:37:00.92 AttributeError: 'unicode' object has no attribute 'get'
05-03 10:37:00.92 
```

**Comment by justparking** [comment]
I don't think this has anything to do with long name. In this case it just looks like the `memberStatus` object it is dealing with is a string but it expected a an object/map/dictionary.
