### ISSUE TITLE
Gallery Group Nodel delete member

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#21]
Deleted a member from a gallery node with group support and received this error.

`10-03 10:29:49.26 ('main' and '@after_main' functions completed cleanly)
10-03 10:30:00.59 PowerOn requested.
10-03 11:01:45.15 (closing this interpreter...)
10-03 11:01:45.15 (clean up complete)
10-03 11:01:45.21 (Python and Node script loaded in 56ms; calling 'main'...)
10-03 11:01:45.21 Started!
10-03 11:01:45.21 'main' completed with errors - Traceback (most recent call last):
10-03 11:01:45.21   File "C:\Nodel\.\nodes\BodyWorksGallery\.nodel\nodetoolkit.py", line 283, in processAfterMainFunctions
10-03 11:01:45.21     f()
10-03 11:01:45.21   File "C:\Nodel\.\nodes\BodyWorksGallery\script.py", line 282, in extendGroup
10-03 11:01:45.21     desirePower.addEmitHandler(handlePower)
10-03 11:01:45.21 AttributeError: 'NoneType' object has no attribute 'addEmitHandler'
10-03 11:01:45.21 `

**Comment by scienceworld** [comment]
problem exists when legacy support is enabled, and there are no members.  disabling legacy support corrected issue.

**Comment by rhulse** [comment]
@scienceworld I have seen a similar issue when deleting members - in may case, the old data was not removed from the config json file, so the group node was still looping over it. Perhaps check the config in the editor for the node to see if the old data is still there.

**Comment by scienceworld** [comment]
i'm sure that was the case.  either way turning off legacy support got around the problem.

**Comment by scienceworld** [comment]
got it to a position where deleting the members caused the entire recipe to error out and no longer function.  I ended up re-adding the member to get it working again.  haven't tried cleaning out the config.json but we ended up having a gallery that didnt power on or off for a few days as a result of not catching this.

**Comment by scienceworld** [comment]
confirmed that a gallery node with groups bolted on with no members causes the recipe to no longer present any actions.
