### ISSUE TITLE
Samsung Display Control issue

### ISSUE THREAD

**Issue by scienceworld** [museumsvictoria/nodel-recipes#39]
We're using the samsung display node and we're getting a lot of console messages while the node is polling the device for status.  the node works, but its verbosely spitting out messages.

```
05-06 17:17:14.69 
05-06 17:17:59.70 (requestQueue) Traceback (most recent call last):
05-06 17:17:59.70   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 393, in handleResp
05-06 17:17:59.70     checkHeader(arg)
05-06 17:17:59.70   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-06 17:17:59.70     raise Exception('Bad acknowledgement')
05-06 17:17:59.70 Exception: Bad acknowledgement
05-06 17:17:59.70 
05-06 17:18:11.99 power: state (still) does not match desired, setting to "Off"
05-06 17:18:11.99 forcePower("Off")
05-06 17:18:30.94 power: done checking state - states match or desired is none)
05-07 03:13:34.83 (requestQueue) Traceback (most recent call last):
05-07 03:13:34.83   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 451, in <lambda>
05-07 03:13:34.83     queue.request(lambda: tcp.send('\xaa%s%s' % (msg, chr(checksum))), lambda resp: checkHeader(resp, lambda: serialNumberEvent.emit(resp[6:-4])))
05-07 03:13:34.83   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-07 03:13:34.83     raise Exception('Bad acknowledgement')
05-07 03:13:34.83 Exception: Bad acknowledgement
05-07 03:13:34.83 
05-07 03:13:34.85 (requestQueue) Traceback (most recent call last):
05-07 03:13:34.85   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 462, in <lambda>
05-07 03:13:34.85     queue.request(lambda: tcp.send('\xaa%s%s' % (msg, chr(checksum))), lambda resp: checkHeader(resp, lambda: softwareVersionEvent.emit(resp[6:-1])))
05-07 03:13:34.85   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-07 03:13:34.85     raise Exception('Bad acknowledgement')
05-07 03:13:34.85 Exception: Bad acknowledgement
05-07 03:13:34.85 
05-07 09:01:43.73 power: state (still) does not match desired, setting to "On"
05-07 09:01:43.73 forcePower("On")
05-07 09:02:04.91 TCP disconnected
05-07 09:02:04.91 TCP timeout
05-07 09:02:08.73 power: state (still) does not match desired, setting to "On"
05-07 09:02:08.73 forcePower("On")
05-07 09:02:08.73 protocol timeout; flushing buffer
05-07 09:02:27.45 TCP connected
05-07 09:02:28.45 protocol timeout; flushing buffer
05-07 09:02:33.73 power: state (still) does not match desired, setting to "On"
05-07 09:02:33.73 forcePower("On")
05-07 09:02:58.46 power: done checking state - states match or desired is none)
05-07 09:03:10.04 (requestQueue) Traceback (most recent call last):
05-07 09:03:10.04   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 393, in handleResp
05-07 09:03:10.04     checkHeader(arg)
05-07 09:03:10.04   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-07 09:03:10.04     raise Exception('Bad acknowledgement')
05-07 09:03:10.04 Exception: Bad acknowledgement
05-07 09:03:10.04 
05-07 09:03:55.04 (requestQueue) Traceback (most recent call last):
05-07 09:03:55.04   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 393, in handleResp
05-07 09:03:55.04     checkHeader(arg)
05-07 09:03:55.04   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-07 09:03:55.04     raise Exception('Bad acknowledgement')
05-07 09:03:55.04 Exception: Bad acknowledgement
05-07 09:03:55.04 
05-07 09:04:40.05 (requestQueue) Traceback (most recent call last):
05-07 09:04:40.05   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 393, in handleResp
05-07 09:04:40.05     checkHeader(arg)
05-07 09:04:40.05   File "C:\Nodel\.\nodes\OurWorldArtTV\script.py", line 491, in checkHeader
05-07 09:04:40.05     raise Exception('Bad acknowledgement')
05-07 09:04:40.05 Exception: Bad acknowledgement
```

**Comment by justparking** [comment]
Can you raise the logging level so we can get a snippet of the data being received? It might be a setID issue.

Also, what model Samsung?

**Comment by scienceworld** [comment]
model: LH85QMNEBGC

Can you describe the instructions for changing logging?

**Comment by justparking** [comment]
Purely a Node specific thing.:

* **Advanced**: ✓
* **DebugShowLogging**: ✓ 

![image](https://user-images.githubusercontent.com/5266533/57341529-1f82e200-717e-11e9-8f42-2607dcf9c5f4.png)
_(remember to emit signal)_

**Comment by scienceworld** [comment]
There was a nodel

**Comment by justparking** [comment]
With the Samsang, issues with SetIDs can make the Samsung's very fiddly to get going.

Other than than, make sure you keep up with latest updates to recipe even if most updates involve new supported operations rather than stability.

Have not received any further comments so closing.
